##
# Failure Notification Handler (FNH) daemon log filename variable refresh.
#
# Include program log file path when appropriate.
#
# Dynamically enables or disables the program log file path link in the
# failure email generated by the FNH script, which is triggered by
# the Failure Notification Handler daemon. Depending on whether or not a
# program log file is currently active determines how this subroutine
# adjusts the related FNH daemon variable.
##

function refresh_failure_handler_daemon ()
{
	# skip when FNH service not utilized
	[ "$enable_failure_notification_service" != true ] && return 0

	[ -z "$failure_handler_daemon_service_filename" ] && return 1

	##
	# The log_filename pointer may or may not be commented out.
	# And while the file should be formatted consistently, the
	# commands below allow for the possibility its lines may
	# or may not contain leading white space. Whether or not
	# the line is remmed out is irrelevant and will not affect
	# the logic below.
	##

	# dynamically set log file echo behavior on or off
	if [ -n "$log_filename" ] && [ "$log_file_active" = true ]; then # / assign current $log_filename value
		sed -i 's%^\s*#\?\s*Environment="log_filename=.*%Environment="log_filename='"$log_filename"'"%I' "$failure_handler_daemon_service_filename"
	else # 1/ disable copying alert to program log when log file does not exist or should not be applied
		sed -i 's%^\s*#\?\s*Environment="log_filename=.*%# Environment="log_filename="%I' "$failure_handler_daemon_service_filename"
	fi # 1/
}
