# email alerts to user
function send_email_alert ()
{
	local message
	local summary
	local verbose

	message="$1"	# message to send to user
	summary="$2"	# email is a summary of information when non-null
	verbose="$3"	# include log dump when = true

	# email the admin if set in preferences
	[ "$email_alerts" != true ] && return

	if [ -z "$message" ]; then # 1/
		debug_print 3 warn "Aborted sending alert email because email body (alert message) is empty."
		return
	fi # 1/

	debug_print 2 "Sending email alert to system admin."

	# email all data in body of email via sendmail, which allows HTML header to force monospace
	# font for when recipient views the email; mailx does not; postfix by iteslf does not
	(
		printf "From: Fan Controller <%s>\n" "$email"
		printf "To: %s\n" "$email"
		printf "Subject: Fan Controller Message from:$([ -n "$server_id" ] && printf " %s (" "$server_id") %s %s $([ -n "$server_id" ] && printf ")")\n" "$mobo_manufacturer" "$mobo_model"
		printf "MIME-Version: 1.0\nContent-Type: text/html; charset=utf-8\nContent-Disposition: inline\n<html>\n<body>\n<pre style=\"font: monospace\">\n"
		printf "Status Alert Report (SAR) generated by $program_name on server ID \"%s\"\n" "$server_id"
		printf "This report was automatically generated.\n"

		if [ "$summary" = true ]; then # 1/
			printf "\n----------------------------------------  Summary Report ----------------------------------------\n\n"
			printf "%s\n" "$message"
			printf "\n-------------------------------------------------------------------------------------------------\n\n"
		else # 1/
			printf "\nThe following important message has occurred:\n\n"
			printf "%s\n" "$message"
		fi # 1/

		##
		# Show log tail, provided debug mode is requested and a log file exists.
		# Display last 10 lines of log.
		#
		# If any value is specified as 2nd subroutine call argument, skip this step.
		##

		if [ "$verbose" = true ] && [ -n "$log_filename" ]; then # 2/
			printf "\n-------------------------------------------------------------------------------------------------\n"
			printf "Log tail: %s\n\n" "$log_filename"
			tail -n 10 "$log_filename"
		fi # 2/

		printf "</pre>\n</body>\n</html>\n" # footer
	) | sendmail -t
}
